name: xformers-torch
channels:
  - python==3.9.7
  - defaults
dependencies:
  - torchvision=0.12.0
  - pytorch==1.11.0
  - pandas==1.4.2
  - matplotlib==3.5.1
  - scikit-learn==1.0.2
  - scipy==1.7.3
  - statsmodels==0.13.2
- pip:
    - einops==0.4.1
    - opencv-python==4.5.5.64
    - jupyter==1.0.0
    - biopython==1.79
    - pysam==0.18.0
